/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadYUsoDeDatosRouteImport } from './routes/politica-de-privacidad-y-uso-de-datos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PoliticaDePrivacidadYUsoDeDatosRoute =
  PoliticaDePrivacidadYUsoDeDatosRouteImport.update({
    id: '/politica-de-privacidad-y-uso-de-datos',
    path: '/politica-de-privacidad-y-uso-de-datos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/politica-de-privacidad-y-uso-de-datos': typeof PoliticaDePrivacidadYUsoDeDatosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/politica-de-privacidad-y-uso-de-datos': typeof PoliticaDePrivacidadYUsoDeDatosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/politica-de-privacidad-y-uso-de-datos': typeof PoliticaDePrivacidadYUsoDeDatosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/politica-de-privacidad-y-uso-de-datos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/politica-de-privacidad-y-uso-de-datos'
  id: '__root__' | '/' | '/admin' | '/politica-de-privacidad-y-uso-de-datos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PoliticaDePrivacidadYUsoDeDatosRoute: typeof PoliticaDePrivacidadYUsoDeDatosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidad-y-uso-de-datos': {
      id: '/politica-de-privacidad-y-uso-de-datos'
      path: '/politica-de-privacidad-y-uso-de-datos'
      fullPath: '/politica-de-privacidad-y-uso-de-datos'
      preLoaderRoute: typeof PoliticaDePrivacidadYUsoDeDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PoliticaDePrivacidadYUsoDeDatosRoute: PoliticaDePrivacidadYUsoDeDatosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
